apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: rabbitmq  # Updated to match the Service name
  replicas: 1  # Explicitly set replicas (adjust as needed)
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - name: http
              protocol: TCP
              containerPort: 15672
            - name: amqp
              protocol: TCP
              containerPort: 5672
          envFrom:
            - configMapRef:
                name: rabbitmq-configmap
            - secretRef:
                name: rabbitmq-secret
          volumeMounts:
            - mountPath: "/var/lib/rabbitmq"
              name: rabbitmq-volume
  volumeClaimTemplates:  # Switched to volumeClaimTemplates for dynamic PVC provisioning
    - metadata:
        name: rabbitmq-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
