apiVersion: apps/v1
kind: Deployment
matadata:
  name: gateway
  labels:
    app: gateway
spec:
  replica: 2
  selector:
    matchLabels:
      app: gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: gateway
    spec: containers:
      - name: gateway
        image: zibizib/gateway
        envFrom:
          - configMapRef:
              name: gateway-configmap
          - secretRef:
              name: gateway-secret